apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
  namespace: pacman
  labels:
    app: pacman
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pacman
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: docker.io/2ffs2nns/pacman:bdb4281
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pacman-service
  namespace: pacman
spec:
  selector:
    app: pacman
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer

